[config]
reload_apps = true

[config.reload_apps_list]
# waybar = true
# kitty = true
# gtk_theme = true

[templates.sway]
input_path = '~/.config/matugen/templates/sway-colors.conf'
output_path = '~/.config/sway/config.d/colors.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel-colors.ini'
output_path = '~/.config/fuzzel/fuzzel-colors.ini'


[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

