return {
	"m4xshen/hardtime.nvim",
	dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
	opts = {
		disable_mouse = false,
		disabled_filetype = {
			"NvimTree",
			"TelescopePrompt",
			"aerial",
			"alpha",
			"checkhealth",
			"dapui*",
			"Diffview*",
			"Dressing*",
			"help",
			"httpResult",
			"lazy",
			"lspinfo",
			"Neogit*",
			"mason",
			"neotest%-summary",
			"minifiles",
			"neo%-tree*",
			"netrw",
			"noice",
			"notify",
			"prompt",
			"qf",
			"query",
			"oil",
			"undotree",
			"trouble",
			"Trouble",
			"fugitive",
			"dashboard",
			"dapui_stacks",
			"dapui_console",
			"dapui-repl",
			"dapui_watches",
			"dapui_breakpoints",
		},
	},
}
