import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font.bold]
family = "DejaVuSansM Nerd Font"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font"
style = "Bold Italic"

[font.italic]
family = "DejaVuSansM Nerd Font"
style = "Italic"

[font.normal]
family = "DejaVuSansM Nerd Font"
style = "Regular"

[window]
opacity = 0.8
