[colors.primary]
background = '#171216'
foreground = '#ebdfe6'

[colors.cursor]
text = '#ebdfe6'
cursor = '#d1c3cb'

[colors.vi_mode_cursor]
text = '#171216'
cursor = '#f0b3e8'

[colors.search.matches]
foreground = '#4e444b'
background = '#f6b8a9'

[colors.search.focused_match]
foreground = '#4e444b'
background = '#f0b3e8'

[colors.footer_bar]
foreground = '#4e444b'
background = '#ebdfe6'

[colors.hints.start]
foreground = '#4e444b'
background = '#d9bfd3'

[colors.hints.end]
foreground = '#4e444b'
background = '#d9bfd3'

[colors.selection]
text = '#171216'
background = '#f0b3e8'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#f0b3e8'
yellow = '#7f4d7b'
blue = '#f0b3e8'
magenta = '#f6b8a9'
cyan = '#d9bfd3'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
