[colors.primary]
background = '#161217'
foreground = '#eae0e7'

[colors.cursor]
text = '#eae0e7'
cursor = '#cfc3cd'

[colors.vi_mode_cursor]
text = '#161217'
cursor = '#e8b5ef'

[colors.search.matches]
foreground = '#4c444c'
background = '#f5b7b0'

[colors.search.focused_match]
foreground = '#4c444c'
background = '#e8b5ef'

[colors.footer_bar]
foreground = '#4c444c'
background = '#eae0e7'

[colors.hints.start]
foreground = '#4c444c'
background = '#d6c0d6'

[colors.hints.end]
foreground = '#4c444c'
background = '#d6c0d6'

[colors.selection]
text = '#161217'
background = '#e8b5ef'


[colors.normal]
black = '#181818'
red = '#ffb4ab'
green = '#e8b5ef'
yellow = '#794f81'
blue = '#e8b5ef'
magenta = '#f5b7b0'
cyan = '#d6c0d6'
white = '#BAC2DE'


[colors.bright]
black = '#585B70'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#A6ADC8'


[colors.dim]
black = '#45475A'
red = '#F38BA8'
green = '#A6E3A1'
yellow = '#F9E2AF'
blue = '#89B4FA'
magenta = '#F5C2E7'
cyan = '#94E2D5'
white = '#BAC2DE'
